# Generated by Django 4.0 on 2023-02-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
