# Generated by Django 4.0 on 2023-02-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_user_profile_owner_profile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
