# Generated by Django 4.0 on 2023-02-25 08:49

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('featured_image', models.ImageField(upload_to='Course Images')),
                ('author', models.CharField(max_length=100)),
                ('number_of_lectures', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('STEM', 'STEM'), ('Cloud and AI', 'Cloud and AI'), ('ML and AI', 'ML and AI'), ('Design', 'Design'), ('App Development', 'App Development'), ('Project Management', 'Project Management'), ('Data Analysis', 'Data Analysis')], max_length=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('video_link', models.FileField(max_length=900, upload_to='')),
                ('serial_number', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
        ),
    ]
