# Generated by Django 4.0 on 2023-02-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video_link',
            field=models.CharField(max_length=900),
        ),
    ]
