# Generated by Django 4.0 on 2023-02-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_lecture_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
