# Generated by Django 4.0 on 2023-02-27 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='fetured_image',
            new_name='featured_image',
        ),
    ]
