# Generated by Django 4.0 on 2023-02-27 20:43

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0011_rename_fetured_image_post_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('featured_image', models.ImageField(upload_to='post_images')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('publish', 'publish'), ('draft', 'draft')], max_length=300)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
    ]
