# Generated by Django 4.0 on 2023-02-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='answered',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=300, null=True),
        ),
    ]
