# Generated by Django 4.0 on 2023-03-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contact_answered'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=255)),
                ('bio', models.TextField(max_length=500)),
                ('profile_pic', models.ImageField(upload_to='Team Pics')),
                ('twitter_link', models.URLField()),
                ('facebook_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
    ]
