# Generated by Django 4.0 on 2023-03-01 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_teammember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='email_address',
            new_name='email',
        ),
    ]
